Rails.application.routes.draw do
  post 'likes/:post_id/create' => 'likes#create'
  post 'likes/:post_id/destroy' => 'likes#destroy'
  
  get 'login' => 'users#login_form'
  post 'login' => 'users#login'
  post 'logout' => 'users#logout'
  post 'users/:id/update' => 'users#update'
  get 'users/:id/edit' => 'users#edit'
  post 'users/create' => 'users#create'
  get 'signup' => 'users#new'
  get 'users/index' => 'users#index'
  get 'users/:id' => 'users#show'
  get 'users/:id/likes' => 'users#likes'
  
  get 'posts/index' => 'posts#index'
  get 'posts/男子　床' => 'posts#index1'
  get 'posts/鞍馬' => 'posts#index2'
  get 'posts/吊り輪' => 'posts#index3'
  get 'posts/男子　跳馬' => 'posts#index4'
  get 'posts/平行棒' => 'posts#index5'
  get 'posts/鉄棒' => 'posts#index6'
  get 'posts/女子　跳馬' => 'posts#index7'
  get 'posts/段違い平行棒' => 'posts#index8'
  get 'posts/平均台' => 'posts#index9'
  get 'posts/女子　床' => 'posts#index10'
  get 'posts/new' => 'posts#new'
  post 'posts/create' => 'posts#create'
  get 'posts/:id' => 'posts#show'
  get 'posts/:id/edit' => 'posts#edit'
  post 'posts/:id/update' => 'posts#update'
  post 'posts/:id/destroy' => 'posts#destroy'
  get 'comments/:id/show' => 'comments#show'
  post 'posts/:id/comments' => 'comments#create'
  
  get '/' => 'home#top'
  get 'about' => 'home#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
